name: Switch Node version
on: 
  workflow_dispatch:

jobs:
  run-npm-test:
    env:
        NODE_VERSION: 14
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name : setup node
          uses: actions/setup-node@v3
          with:
            node-version: "${{ env.NODE_VERSION }}"
        - name: run test
          shell: bash
          run: |
            npm install
            npm test
        - name: node version
          shell: bash
          run: node -v